### ISSUE TITLE
Use this talk as an opportunity to reinforce documentation reading

### ISSUE THREAD

**Issue by neugierige** [ga-wdi-boston/mongodb-intro#28]
This talk is one that introduces a new technology, and as such it is a good opportunity to reinforce the habit of reading and searching the documentation. 

Specifically, some of the prompts for the code-along / lab can ask developers to utilize some of the operators that were _not_ introduced in the demo.

**Comment by jrhorn424** [comment]
That was certainly an explicit intent on many trainings in this unit. I can't say with certainty whether it's something that has happened with this lesson in the cohorts I've been a part of since 010.

**Comment by MicFin** [comment]
The talk lists documentation before each step in the CRUD process.  Even with the mongodb documentation being down because of AWS S3 outage, we still used documentation by looking up other sources that explain how to use a command like stackoverflow.  I think the way the talk is set up, it very explicitly encourages using the documentation for both the consultant and the developers.  @jrhorn424 I think this could be closed.

**Comment by jrhorn424** [comment]
After reviewing the README, I concur.

@MicFin I'm going to close this issue. Would you please add any notes you have about delivery (such as clearly referencing documentation) to a delivery notes page in the wiki. Consult with @raq929 if you're curious as to how to do that.
